-- Expressions denote values. Expressions in Lua include the numeric constatns and string literals, variables, unary 
-- and binary operations, and function calls. 
-- Expressions can be also unconventional function definitions and table constructors
