-- Operator precedence in Lua follow the table below, from the higher to the lower priority:
-- ^
-- not - (unary)
-- * / 
-- + - 
-- ..
-- < > <= >= ~= ==
-- and 
-- or

-- When in doubt, always use explicit parentheses. It is easier than looking up in the manual and probably you will
-- have the same doubt when you read the code again.
