-- Lua supports an almsot conventional set of statements, similar to those in C. The conventional statements include
-- assignment, control structures, and procedure calls. Lua also supports some not so conventional statements, 
-- such as multiple assignments and local variable declarations
